config/routes.rb
Rails.application.routes.draw do
   

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  #before sidekiq
  #devise_for :users
  # sidekiq
  devise_for :users, controllers: { registrations: "users/registrations"}
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  
  #root :to => "statics#index"
  #Example of regular route:
  #get 'about' => 'pages#about', as: 'about'
  #get '/about' => 'statics#about', :as => :about
  get 'about' => 'about#index', as: 'about'
  get 'settings/index'
  #get 'movies/index_search' => 'movies#index_search'
  #Example resource route
  resources :peliculas do
    resources :comentarios 
  end
  
  resources :settings
  resources :charges
  resources :select_movies, only: :index
  
  #root 'peliculas#index', as: 'home'
  #added for method root_path (search)
  root :to => "statics#index"

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/payment_select_controller.rb
class PaymentSelectController < ApplicationController
    
	def select_plan
		@peliculafind = Pelicula.find(params[:pelicula])
	end

  	def select_monthly_subscription
  	end

end

app/helpers/payment_select_helper.rb
module PaymentSelectHelper
end

app/views/payment_select/select_monthly_subscription.html.erb
<style>
.card {
  padding-top: 20px;
  margin: 10px 0 20px 0;
  background-color: #ffffff;
  border: 1px solid #d8d8d8;
  border-top-width: 0;
  border-bottom-width: 2px;
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
  -webkit-box-shadow: none;
     -moz-box-shadow: none;
          box-shadow: none;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}


.card.hovercard {
  position: relative;
  width: 300px;
  padding-top: 0;
  overflow: hidden;
  text-align: center;
  background-color: #fff;
}

.card.hovercard img {
  width: 300px;
  height: 200px;
}

.card.hovercard .avatar {
  position: relative;
  top: -40px;
  margin-bottom: -40px;
}

.card.hovercard .avatar img {
  width: 80px;
  height: 80px;
  max-width: 80px;
  max-height: 80px;
  -webkit-border-radius: 50%;
     -moz-border-radius: 50%;
          border-radius: 50%;
}

.card.hovercard .info {
  padding: 4px 8px 10px;
}

.card.hovercard .info .title {
  margin-bottom: 4px;
  font-size: 24px;
  line-height: 1;
  color: #262626;
  vertical-align: middle;
}

.card.hovercard .info .desc {
  overflow: hidden;
  font-size: 12px;
  line-height: 20px;
  color: #737373;
  text-overflow: ellipsis;
}

.card.hovercard .bottom {
  padding: 0 20px;
  margin-bottom: 17px;
}

.card.people .card-bottom {
  position: absolute;
  bottom: 0;
  left: 0;
  display: inline-block;
  width: 100%;
  padding: 10px 20px;
  line-height: 29px;
  text-align: center;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}


</style>

 

<div class="container">
<h2 class="jumbotron text-center">Select Monthly Subscription</h2>
<br>
 

	<div class="col-xs-4">

		 	<div class="card hovercard">
			   	<img src="http://www.lamasperrona.com.mx/perrona/system/storage/serve/11180/sabes-cuando-es-la-calidad-de-una-pelicula-en-internet-mejor-o-peor-2.jpg" alt=""/>
				   <div class="avatar">
				      <img src="http://placehold.it/80X80/333333/&text=Head" alt="" />
				   </div>
				   <div class="info">
				      <div class="title">
				         9.99 Euros/mes
				      </div>
				      <div class="desc">Lorem ipsum</div>
				      <div class="desc">Lorem ipsum</div>
				      <div class="desc">Lorem ipsum</div>
				   </div>
				   <div class="bottom">
				      <button class="btn btn-default">Pay Now</button>
				   </div>
			</div> 

	</div><!-- END COL-XS-4 -->
	<div class="col-xs-4">
		 

		 	<div class="card hovercard">
			   	<img src="http://cdn3.computerhoy.com/sites/computerhoy.com/files/styles/fullcontent/public/rankings/peliculas-semana-santa.jpg?itok=GKnrBl5J" alt=""/>
				   <div class="avatar">
				      <img src="http://placehold.it/80X80/333333/&text=Head" alt="" />
				   </div>
				   <div class="info">
				      <div class="title">
				         12.99 Euros/mes
				      </div>
				      <div class="desc">Lorem ipsum</div>
				      <div class="desc">Lorem ipsum</div>
				      <div class="desc">Lorem ipsum</div>
				   </div>
				   <div class="bottom">
				      <button class="btn btn-default">Pay Now</button>
				   </div>
			</div>
			  
	</div><!-- END COL-XS-4 -->

	<div class="col-xs-4">
		
		 	<div class="card hovercard">
			   	<img src="http://st-listas.20minutos.es/images/2013-04/360421/list_321px.jpg?1367506747" alt=""/>
				   <div class="avatar">
				      <img src="http://placehold.it/80X80/333333/&text=Head" alt="" />
				   </div>
				   <div class="info">
				      <div class="title">
				         19.99 Euros/mes
				      </div>
				      <div class="desc">Lorem ipsum</div>
				      <div class="desc">Lorem ipsum</div>
				      <div class="desc">Lorem ipsum</div>
				   </div>
				   <div class="bottom">
				      <button class="btn btn-default">Pay Now</button>
				   </div>
			</div> 

	</div><!-- END COL-XS-4 -->

</div><!-- END container -->

app/views/payment_select/select_plan.html.erb
<div class="container">
<h2 class="jumbotron text-center">Payment Plan Select</h2>
<br>

	<div class="row" style="margin: 0px auto; border:1px solid gray;padding: 10px;">
	<%= link_to new_charge_path(amount: @peliculafind.precio) do %>
		<div class="col-md-6 well" style="width: 450px;height: 480px;border-radius: 10px; margin: 15px;">
			<div class="text-center">
				<img class="img-responsive" src="https://us.123rf.com/450wm/jpgon/jpgon1610/jpgon161001082/63844924-illustration-of-an-isolated-film-camera-icon-with--the-text-buy-now.jpg?ver=6" style="width:80%;">
				<h3> Comprar: <%= @peliculafind.name %> </h3>
				<h3>Precio: <%= @peliculafind.precio/100.0 %>€</h3>
			</div>
		</div>		
	<% end %>	
	<%= link_to select_monthly_subscription_path(@peliculafind.id) do %>
		<div class="col-md-6 well" style="width: 450px;height: 480px;border-radius: 10px; margin: 15px;">
			<div class="text-center">
				<img class="img-responsive" src="http://st.depositphotos.com/2274151/4233/i/950/depositphotos_42330095-stock-photo-subscribe-now-blue-grunge-round.jpg" style="width:80%;">
				<h2> SUBSCRIBE NOW</h2>
			</div>
		</div>	
	<% end %>	
</div> 

<%=debug params %>

</div>