config/routes.rb
Rails.application.routes.draw do
   

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  #before sidekiq
  #devise_for :users
  # sidekiq
  devise_for :users, controllers: { registrations: "users/registrations"}
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  
  #root :to => "statics#index"
  #Example of regular route:
  #get 'about' => 'pages#about', as: 'about'
  #get '/about' => 'statics#about', :as => :about
  get 'about' => 'about#index', as: 'about'
  get 'settings/index'
  #get 'movies/index_search' => 'movies#index_search'
  #Example resource route
  resources :peliculas do
    resources :comentarios 
  end
  
  resources :settings
  resources :charges
  resources :select_movies, only: :index
  
  #root 'peliculas#index', as: 'home'
  #added for method root_path (search)
  root :to => "statics#index"

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_boxsearchs.html.erb
<div class="container"> 
<!-- BUSQUEDA POR NAME DE PELICULA --> 
<div class="row" style="margin-top:110px;">
 <div class="col-sm-6" style="text-align:center;">
   <%= form_tag(root_path, :method => "get", id: "search-form", html: { class: 'form-horizontal col-sm-4'} ) do %>
       <%= text_field_tag :search, params[:search], placeholder:"Buscar por Pelicula" %>
       <%= submit_tag "Search", :name => nil %> 
   <% end %>
 </div><!-- end col-sm-6 -->
<!-- BUSQUEDA POR EL GENERO EN UN DROPDOWN SELECT DE PELICULA --> 
 <div class="col-sm-6" style="text-align:center;">
    <div class="form-inline">
          <%= form_tag(root_path, :method => "get", id: "genre") do %>
            <%= select_tag :search_genre, ("<option> Seleccionar Genero</option><br><option>ACTION</option><option>ADVENTURE</option><option>COMEDY</option><option>CRIME</option><option>DRAMA</option><option>HISTORICAL</option><option>HORROR</option><option>MUSICALS</option><option>SCIENCE-FICTION</option><option>WAR</option><option>WESTERNS</option>").html_safe, class: 'btn btn-primary', style:"width:225px;", :onchange => "this.form.submit()"%>
          <% end %>
    </div> 
  </div> <!-- end col-sm-6 --> 
</div> <!-- end row -->
<!-- BUSQUEDA POR AÑO DE LA PELICULA --> 
<div class="row">
 <div class="col-sm-6" style="text-align:center;">
     <%= form_tag(root_path, :method => "get", id: "search-year-form", html: { class: 'form-horizontal col-sm-4'} ) do %>
     <%= text_field_tag :search_year, params[:search_year], placeholder: "Buscar por Año"  %>
       <%= submit_tag "Search", :year => nil %> 
   <% end %>
 </div> <!-- end col-sm-6 --> 
</div> <!-- end row -->
</div> <!-- end container -->

app/views/shared/_flash_messages.html.erb
<div class="row">
  <div class="col-sm-12">
    <% flash.each do |type, message| %>
    <% unless message.blank? %>
    <div id="flashmensaje" class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message.html_safe %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
 
<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#flashmensaje').remove();
  }, 5000);
})
</script>

app/views/shared/_footer.html.erb
 <div class="estilosapp2">
 
<footer id="footer">

<div class="row">

<div class="col-lg-3 col-md-3 relleno size12">
  <a href="">Help</a> </br>
  <a href="">About Rotten Tomatoes</a> </br>
  <a href="">What's the Tomatoes</a> </br>
  <a href="">Jobs</a> </br>
  <a href="">Advertise</a> </br>
</div>  <!-- col-lg-3 -->


<div class="col-lg-3 col-md-3 relleno size12">
  <a href="">Critic Submission</a> </br>
  <a href="">API</a> </br>
  <a href="">Licensing</a> </br>
  
</div>  <!-- col-lg-3 -->

<div class="col-lg-6 col-md-6 relleno">
 <p class="white size18"><b>FOLLOW US</b></p>
 <a class="fa fa-2x fa-twitter margin10le" href="" title="Twitter"></a>
 <a class="fa fa-2x fa-facebook-square margin10le" href="" title="Twitter"></a>
 <a class="fa fa-2x fa-google-plus margin10le" href="" title="Twitter"></a>
 <a class="fa fa-2x fa-youtube-play margin10le" href="" title="Twitter"></a>
 <a class="fa fa-2x fa-tumblr margin10le" href="" title="Twitter"></a>
</div>  <!-- col-lg-6 -->


</div> <!-- row --> 


</footer>  

</div><!-- end estilosapp2 -->

app/views/shared/_header.html.erb
 <div class="estilosapp2">
   

  <!-- NAVBAR BEGIN  -->
  <nav id="logo" class="navbar navbar-fixed-top navbar-default" role="navigation">
   
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsable">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- BRAND -->
      <%=link_to "", root_path, class:"navbar-brand" ,id:"brand-logo" %> 
    </div>
      <!-- SEARCH BOX -->
    <div class="col-sm-7 col-md-7">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" size="50" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>         
        </form>
         
    </div>

    <!-- NAVBAR DROPDOWNS-->
    <div class="collapse navbar-collapse" id="navbar-collapsable">
      <ul class="nav navbar-nav foo" id="menu">
        
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">MOVIES & DVDs<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header bgreen">MOVIES & DVDs</li>
            <b class="caret"></b>
            <li>  <%= link_to 'Peliculas', peliculas_path %> </li>
            <li>     </li>
            <li><a href="/three">Three</a></li>
            <li class="divider"></li>
            <li><a href="/admin">Admin Dashboard</a></li>
            <li><a href="/admin/users">Users</a></li>
          </ul>
        </li> <!-- end dropdown -->
 
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">TV<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header bgreen">TV</li>
            <b class="caret"></b>
            <li><a href="/one">One</a></li>
            <li><a href="/two">Two</a></li>
            <li><a href="/three">Three</a></li>
            <li class="divider"></li>
            <li><a href="/admin">Admin Dashboard</a></li>
            <li><a href="/admin/users">Users</a></li>
          </ul>
        </li> <!-- end dropdown -->
 
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">NEWS<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header bgreen">NEWS</li>
            <b class="caret"></b>
            <li><a href="/one">One</a></li>
            <li><a href="/two">Two</a></li>
            <li><a href="/three">Three</a></li>
            <li class="divider"></li>
            <li><a href="/admin">Admin Dashboard</a></li>
            <li><a href="/admin/users">Users</a></li>
          </ul>
        </li> <!-- end dropdown -->
 
      </ul>
      <ul class="nav navbar-nav navbar-right" align="right">
      
           <li><%= link_to "Nosotros", about_path, style:"float:left; color:white" %></li> 
           
           <% if user_signed_in? %> 
            <li class="dropdown"> 
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a> 
              <ul class="dropdown-menu"  style="padding: 20px; ">
               <li class="dropdown-header bgreen">PROFILE</li>
                
               <li> <%= link_to '<i class="fa fa-address-book"></i>&nbsp;Settings'.html_safe, settings_path, class:"btn btn-primary size13 white", style:"margin-top: 15px; margin-bottom: 5px;" %></li>   
               <li><%= link_to '<i class="fa fa-sign-out fa-3"></i>&nbsp;Sign Out'.html_safe, destroy_user_session_path, method: :delete, class:"btn btn-danger size13 white" %>  </li>   
              </ul> 
            </li> <!-- end dropdown --> 
           <% else %> 
             <li><%=link_to "Login", new_user_session_path, style:"color:white" %> </li>
             <li><%=link_to "Sign up", new_user_registration_path, style:"color:white" %> </li> 
           <% end %> 
      </ul>

    </div> <!-- collapse navbar-collapse -->
  </div>
</nav>  <!-- end nav --> 
</div>  <!-- end estilosapp2 -->