config/routes.rb
Rails.application.routes.draw do
   

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  #before sidekiq
  #devise_for :users
  # sidekiq
  devise_for :users, controllers: { registrations: "users/registrations"}
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  
  #root :to => "statics#index"
  #Example of regular route:
  #get 'about' => 'pages#about', as: 'about'
  #get '/about' => 'statics#about', :as => :about
  get 'about' => 'about#index', as: 'about'
  get 'settings/index'
  #get 'movies/index_search' => 'movies#index_search'
  #Example resource route
  resources :peliculas do
    resources :comentarios 
  end
  
  resources :settings
  resources :charges
  resources :select_movies, only: :index
  
  #root 'peliculas#index', as: 'home'
  #added for method root_path (search)
  root :to => "statics#index"

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
 
  has_many :comentarios, dependent: :destroy
  validates :director, presence: true, uniqueness: {message: "El nombre del Director ha de ser unico"}
  	

def self.search(search)
  where("name like ?", "%" + "%#{search}%" + "%")
end

def self.search_year(search_year)
  where(year: search_year)
end


def self.search_genre(search_genre)
  where(genre: search_genre)
end
 

end
 

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController

def index
	@peliculas = Pelicula.all
end

def show
	@pelicula = Pelicula.find(params[:id]) 
end 

def new
    @pelicula = Pelicula.new  
end

def create

  @pelicula = Pelicula.new(pelicula_params)
   if @pelicula.save 
    flash[:danger] = t('flash.message2')
    redirect_to peliculas_path
  else
    render 'new'
  end
end
  
 


def edit
  @pelicula = Pelicula.find(params[:id])
end

def update
  @pelicula = Pelicula.find(params[:id])

  if @pelicula.update_attributes(pelicula_params)
       redirect_to peliculas_path
  else
    render :edit
  end
end


def destroy
   @pelicula = Pelicula.find(params[:id])
   @pelicula.destroy
   redirect_to peliculas_path
end


private
def pelicula_params
  params.require(:pelicula).permit(:name, :director, :actor, :email_contact,
  :oscar, :category, :stars, :country, :year, :revenue_amount, :url, :genre, :precio)
end  
 

end
 

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/views/peliculas/edit.html.erb
  
  
 
<div class="estilosapp2">
 
 
 <!-- PARCIAL HEADER --> 
 <%= render "shared/header" %>


<div class="container"> 
 


<div class="controladorej2">

<div class="box">
    <div class="alert"><i class="fa fa-th-large fa-1x color-blue"></i>&nbsp;Editar Pelicula</div> 
        <%= form_for(@pelicula) do |f| %>
        <div class="field">
            <%= f.text_field :name, placeholder: "Nombre", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.text_field :director, placeholder: "Director", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.text_field :actor, placeholder: "Actor", class:"form-control" %>
        </div> 
         <div class="field">
            <%= f.text_field :email_contact, placeholder: "Email", class:"form-control" %>
        </div>  
        <div class="field">
            <%= f.text_field :stars, placeholder: "Stars", class:"form-control" %>
        </div> 
         <div class="field">
           <%= f.select :country, options_for_country, :prompt => 'Select Country', class:'form-control' %>
        </div>   
        <div class="field">
            <%= f.text_field :year, placeholder: "Año", class:"form-control" %>
        </div>     
         <div class="field">
           <%= f.select :genre, options_for_genre, :prompt => 'Select Genero', class:'form-control' %>
        </div>  
        <div class="field">
            <%= f.text_field :precio, placeholder: "Precio", class:"form-control" %>
        </div>      
        <div class="field">
            <%= f.text_field :url, placeholder: "URL Imagen", class:"form-control" %>
        </div>      
        <div class="field">
            <%= f.submit "Guardar", class:"btn btn-sm btn-danger white pull-right", style:"margin-top: 15px;" %>
        </div>
    <% end %>
    <%= link_to 'Listado de Peliculas', @pelicula, class:"btn btn-sm btn-primary", style:"margin-top: 15px;" %> 
  <br></br> 
  <ol>
    <li>El nombre no puede estar vacio.</li>
    <li>No permite guardar 2 nombres en la BD con el mismo nombre.</li>
    <li>El apellido no puede estar vacio.</li>
    <li>El email no puede estar vacio.</li>
    <li>El email tiene que tener el formato standard con el signo @</li>
  </ol>  
</div> <!-- end box -->

<div class="row">
     <div class="margin20">
        <%= @pelicula.errors.full_messages.each do |message| %>
            <div class="message be-red white top-space text-center">
                * <%= message %>
            </div>
        <% end %>
    </div>        
</div> <!-- end row -->



<!-- PARCIAL FOOTER --> 
<%= render "shared/footer" %>


</div> <!-- end container -->
  
</div> <!-- end controladorej2 -->
 
  
</div> <!-- end estilosapp2 -->

app/views/peliculas/index.html.erb
 

<div class="estilosapp2">
 
 
 <!-- PARCIAL HEADER --> 
 <%= render "shared/header" %>


<div class="container"> 
 
 
<div class="controladorej2">
 


         <div class="boxp">
            <div class="alert bold size18"><i class="fa fa-home fa-1x color-teal"></i>&nbsp;MOVIES OPENING THIS WEEK</div>  
            <table class="table table-hover table-striped" border="0">
              
              <tbody>
               <% @peliculas.each do |peli| %>
                  <tr>
                    <td>
                      <span class="fa fa-star blue">&nbsp;</span><%= peli.stars %>
                    </td>
                    <td><%= peli.id  %> </td>
                    <td>
                      <%= peli.name %>
                    </td>
                    
                     <td>
                      <%= peli.actor %>
                    </td>
                    <td>
                      <%= peli.year %>
                    </td>
                      <td align="center">
              <%= link_to '', pelicula_path(peli), :title => "Visualizar", :class => 'btn btn-sm btn-success fa fa-1x fa-search', style:"color: white;" %>
              <%= link_to '', edit_pelicula_path(peli), :title => "Editar", :class => 'btn btn-sm btn-primary fa fa-1x fa-edit', style:"color: white;" %>
              <%= link_to '', { action: :destroy, id: peli.id }, method: :delete, :title => "Eliminar",:class => 'btn btn-sm btn-danger fa fa-1x fa-close', style:"color: white;" %>
            </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= link_to 'Nueva Pelicula', new_pelicula_path, title:"Añade una nueva pelicula !!", class:"btn btn-sm btn-danger" %>
</div> <!-- end box -->     

 


<!-- PARCIAL FOOTER --> 
<%= render "shared/footer" %>


</div> <!-- end container -->
  
</div> <!-- end controladorej2 -->
 
  
</div> <!-- end estilosapp2 -->

app/views/peliculas/new.html.erb
  
  

 

<div class="estilosapp2">
 
 
 <!-- PARCIAL HEADER --> 
 <%= render "shared/header" %>


<div class="container"> 
 




<div class="controladorej2">

<div class="box">
    <div class="alert"><i class="fa fa-th-large fa-1x color-blue"></i>&nbsp;Crear Pelicula</div> 
        <%= form_for(@pelicula) do |f| %>
        <div class="field">
            <%= f.text_field :name, placeholder: "Nombre", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.text_field :director, placeholder: "Director", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.text_field :actor, placeholder: "Actor", class:"form-control" %>
        </div> 
        
        <div class="field">
            <%= f.text_field :email_contact, placeholder: "Email", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.text_field :oscar, placeholder: "Oscar (Yes/No)", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.text_field :category, placeholder: "Category", class:"form-control" %>
        </div>  
        <div class="field">
            <%= f.text_field :stars, placeholder: "Stars", class:"form-control" %>
        </div> 

        <div class="field">
           <%= f.select :country, options_for_country, :prompt => 'Select Country', class:'form-control' %>
        </div>   

        <div class="field">
            <%= f.text_field :year, placeholder: "Año", class:"form-control" %>
        </div>    
        <div class="field">
            <%= f.text_field :revenue_amount, placeholder: "Recaudacion", class:"form-control" %>
        </div> 
         <div class="field">
            <%= f.text_field :genre, placeholder: "Genero", class:"form-control" %>
        </div> 
         <div class="field">
            <%= f.text_field :precio, placeholder: "Precio", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.text_field :genre, placeholder: "URL Imagen", class:"form-control" %>
        </div> 
        <div class="field">
            <%= f.submit "Guardar", class:"btn btn-sm btn-danger white pull-right", style:"margin-top: 15px;" %>
        </div>
    <% end %>
    <%= link_to 'Listado de Peliculas', @pelicula, class:"btn btn-sm btn-primary", style:"margin-top: 15px;" %> 
  <br></br> 
  <ol>
    <li>El nombre no puede estar vacio.</li>
    <li>No permite guardar 2 nombres en la BD con el mismo nombre.</li>
    <li>El apellido no puede estar vacio.</li>
    <li>El email no puede estar vacio.</li>
    <li>El email tiene que tener el formato standard con el signo @</li>
  </ol>  
</div> <!-- end box -->

<div class="row">
     <div class="margin20">
        <%= @pelicula.errors.full_messages.each do |message| %>
            <div class="message be-red white top-space text-center">
                * <%= message %>
            </div>
        <% end %>
    </div>        
</div> <!-- end row -->


<!-- PARCIAL FOOTER --> 
<%= render "shared/footer" %>


</div> <!-- end container -->
  
</div> <!-- end controladorej2 -->
 
  
</div> <!-- end estilosapp2 -->

app/views/peliculas/show.html.erb
  

 


<div class="estilosapp2">
 
 
 <!-- PARCIAL HEADER --> 
 <%= render "shared/header" %>


<div class="container"> 
 
 

<div class="controladorej2">


<div class="row">
  <div class="box">
      <div class="alert"><i class="fa fa-th-large fa-1x color-blue"></i>&nbsp;Mostrar Pelicula</div>
        
 
       <%= form_for(@pelicula) do |f| %>

      
  <div class="well"> 
        <div class="field"> 
                <img src="<%= @pelicula.url%>" style="width: 200px; height: 250px;"/>
                <label class="col-sm-2">Imagen:</label>
                 <div class="col-sm-6">
                <input type="text" class="form-control" value="<%= @pelicula.url %>" size="75">
              </div>
        </div> <!-- end field --> 

    </div>

  
         <div class="field">
              <label class="control-label">Id:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.id %>">
           
        </div> <!-- end field -->
       
        <div class="field">
              <label class="control-label">Name:</label>
             
                <input type="text" class="form-control" value="<%= @pelicula.name %>">
             
        </div> <!-- end field -->
       
          <div class="field">
           <label class="control-label">Director:</label>
             
                <input type="text" class="form-control" value="<%= @pelicula.director %>">
            
        </div> <!-- end field -->
        
          <div class="field">
           <label class="control-label">Actor:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.actor %>">
              
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Email Contact:</label>
               
                <input type="text" class="form-control" value="<%= @pelicula.email_contact %>">
              
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Oscar:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.oscar %>">
              
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Categoria:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.category %>">
              
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Stars:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.stars %>">
             
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Country:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.country %>">
              
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Year:</label>
            
                <input type="text" class="form-control" value="<%= @pelicula.year %>">
              
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Revenue Amount:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.revenue_amount %>">
             
        </div> <!-- end field -->
       <div class="field">
           <label class="control-label">Genero:</label> 
                <input type="text" class="form-control" value="<%= @pelicula.genre %>">
              
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">Precio:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.precio %>">
             
        </div> <!-- end field -->
        <div class="field">
           <label class="control-label">URL imagen:</label>
              
                <input type="text" class="form-control" value="<%= @pelicula.url %>">
             
        </div> <!-- end field -->
       <% end %>

      <div class="row">
        <div class="col-lg-12">
          <br/>
       <%= link_to 'Back', peliculas_path, class:"btn btn-sm btn-success pull-right", style:"margin-right: 15px; margin-top: 10px;" %>
     </div>
      </div> <!-- end field -->




<br>



<h2>  Comentarios </h2>
 
     <%= render @pelicula.comentarios %>
 
 
<div class="panel panel-default panelmod1" style=" box-shadow: 1px 2px 3px gray;"> 
<span style="font-size: 2em; margin-left:-7px;margin-bottom: 10px;">Añadir comentarios</span>
</br>
<%= render "comentarios/form" %>
  
<br></br>


</div> <!-- end box -->


<%= link_to 'Editar Pelicula', edit_pelicula_path(@pelicula), class:"btn btn-sm btn-success" %> 
<%= link_to 'Back to Peliculas', peliculas_path, class:"btn btn-sm btn-primary" %>
   





 
    
  <div class="margin20">  
    <br>
    <%= @pelicula.errors.full_messages.each do |message| %>
        <div class="be-red white top-space text-center">
          * <%= message %>
        </div>
    <% end %>
  </div>

</div> <!-- end row -->
 
 
<!-- PARCIAL FOOTER --> 
<%= render "shared/footer" %>


</div> <!-- end container -->
  
</div> <!-- end controladorej2 -->
 
  
</div> <!-- end estilosapp2 -->